name: make and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get -q update
        sudo apt-get -qy install \
            curl build-essential make cmake libc6-dev \
            python3 python3-pip python3-pytest \
            python3-numpy
        cd /usr/bin ; sudo ln -sf py.test-3 py.test

    - name: Run build
      run: make && make test

      
